apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:cluster-gateway:role-grantor
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:cluster-gateway:managedcluster-reader
subjects:
  - kind: ServiceAccount
    name: cluster-gateway-addon-manager
    namespace: {{ .Release.Namespace }}